spin_manifest_version = 2

[application]
authors = ["Gordon Smith <GordonJSmith@gmail.com>"]
description = ""
name = "vitepress"
version = "0.1.1"

[[trigger.http]]
route = "/..."
component = "vitepress"

[component.vitepress]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = ".vitepress/dist/", destination = "/" }]
exclude_files = ["**/node_modules"]

[component.vitepress.build]
command = "npm run build-docs"

[[trigger.http]]
route = "/c"
component = "test-c"

[component.test-c]
source = "test-c/build/http_root_world.wasm"
allowed_outbound_hosts = []

[component.test-c.build]
command = "cmake -S . -B ./build -DCMAKE_TOOLCHAIN_FILE=../vcpkg_installed/x64-linux/wasi-sdk/share/cmake/wasi-sdk.cmake -DCMAKE_BUILD_TYPE=MinSizeRel && cmake --build ./build"
watch = ["**/*.c*"]
workdir = "test-c"

[[trigger.http]]
route = "/rust"
component = "test-rust"

[component.test-rust]
source = "test-rust/target/wasm32-wasip1/release/test_rust.wasm"
allowed_outbound_hosts = []

[component.test-rust.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
workdir = "test-rust"

[[trigger.http]]
route = "/ts/..."
component = "test-ts"

[component.test-ts]
source = "test-ts/dist/test-ts.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = []

[component.test-ts.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
workdir = "test-ts"
