spin_manifest_version = 2

[application]
authors = ["Gordon Smith <GordonJSmith@gmail.com>"]
description = ""
name = "vitepress"
version = "0.5.0"

[variables]
oauth_client_id = { default = "" }
oauth_client_secret = { default = "", secret = true }
oauth_scope = { default = "read:user" }
oauth_redirect_uri = { default = "" }
oauth_admins = { default = "GordonSmith" }
s3_endpoint = { default = "" }
s3_bucket = { default = "" }
s3_label = { default = "" }
s3_access_key = { default = "", secret = true }
s3_secret_key = { default = "", secret = true }

[[trigger.http]]
route = "/..."
component = "vitepress"

[component.vitepress]
source = { url = "https://github.com/spinframework/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = ".vitepress/dist", destination = "/" }]

[component.vitepress.build]
command = "npm run build-docs"

[[trigger.http]]
route = "/c"
component = "test-c"

[component.test-c]
source = "test-c/build/http_root_world.wasm"
allowed_outbound_hosts = ["https://spin-poc.gb-lon-1.linodeobjects.com"]

[component.test-c.variables]
s3_endpoint = "{{ s3_endpoint }}"
s3_bucket = "{{ s3_bucket }}"
s3_label = "{{ s3_label }}"
s3_access_key = "{{ s3_access_key }}"
s3_secret_key = "{{ s3_secret_key }}"

[component.test-c.build]
command = "cmake -S . -B ./build -DCMAKE_TOOLCHAIN_FILE=$PWD/../vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$PWD/../wasi-sdk/share/cmake/wasi-sdk-p3.cmake -DVCPKG_OVERLAY_PORTS=$PWD/../vcpkg_overlays -DVCPKG_OVERLAY_TRIPLETS=$PWD/../vcpkg_overlays -DVCPKG_TARGET_TRIPLET=wasm32-wasip3 -DCMAKE_BUILD_TYPE=MinSizeRel && cmake --build ./build"
watch = ["**/*.c*"]
workdir = "test-c"

[[trigger.http]]
route = "/rust"
component = "test-rust"

[component.test-rust]
source = "test-rust/target/wasm32-wasip1/release/test_rust.wasm"
allowed_outbound_hosts = ["https://random-data-api.fermyon.app"]

[component.test-rust.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
workdir = "test-rust"

[[trigger.http]]
route = "/ts"
component = "test-ts"

[component.test-ts]
source = "test-ts/dist/test-ts.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = []

[component.test-ts.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
workdir = "test-ts"

[[trigger.http]]
route = "/auth/..."
component = "test-oauth"

[component.test-oauth]
source = "test-oauth/target/wasm32-wasip1/release/test_oauth.wasm"
allowed_outbound_hosts = ["https://github.com", "https://api.github.com"]
key_value_stores = ["default"]

[component.test-oauth.variables]
client_id = "{{ oauth_client_id }}"
client_secret = "{{ oauth_client_secret }}"
scope = "{{ oauth_scope }}"
redirect_uri = "{{ oauth_redirect_uri }}"
admins = "{{ oauth_admins }}"

[component.test-oauth.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
workdir = "test-oauth"
