spin_manifest_version = 2

[application]
authors = ["Gordon Smith <GordonJSmith@gmail.com>"]
description = ""
name = "vitepress"
version = "0.2.0"

[[trigger.http]]
route = "/..."
component = "vitepress"

[component.vitepress]
source = { url = "https://github.com/spinframework/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = ".vitepress/dist/", destination = "/" }]
exclude_files = ["**/node_modules"]

[component.vitepress.build]
command = "npm run build-docs"

[[trigger.http]]
route = "/c"
component = "test-c"

[component.test-c]
source = "test-c/build/http_root_world.wasm"
allowed_outbound_hosts = []

[component.test-c.build]
command = "cmake -S . -B ./build -DCMAKE_TOOLCHAIN_FILE=../vcpkg_installed/x64-linux/wasi-sdk/share/cmake/wasi-sdk-p2.cmake -DCMAKE_BUILD_TYPE=MinSizeRel && cmake --build ./build"
watch = ["**/*.c*"]
workdir = "test-c"

[[trigger.http]]
route = "/rust"
component = "test-rust"

[component.test-rust]
source = "test-rust/target/wasm32-wasip2/release/test_rust.wasm"
allowed_outbound_hosts = ["https://random-data-api.fermyon.app"]

[component.test-rust.build]
command = "cargo build --target wasm32-wasip2 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
workdir = "test-rust"

[[trigger.http]]
route = "/ts/..."
component = "test-ts"

[component.test-ts]
source = "test-ts/dist/test-ts.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = []

[component.test-ts.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
workdir = "test-ts"

# [[trigger.http]]
# route = "/login"
# component = "frontend"
# executor = { type = "wasip3-unstable" }

# [component.frontend]
# source = "p3/authed_app.wasm"  # for P3 we have to post-process compose in build.sh
# allowed_outbound_hosts = ["https://github.com", "https://api.github.com"]

# [component.frontend.build]
# command = "./build.sh"
# Unused because for now we have to precompose in build.sh
# [component.frontend.dependencies]
# "wasi:http/incoming-handler@0.2.0" = { path = "target/wasm32-wasip1/release/example.wasm" }
